<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit382780e3525e50bc2a5e7087d7524cae
{
    public static $prefixLengthsPsr4 = array (
        'c' => 
        array (
            'cooking\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'cooking\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit382780e3525e50bc2a5e7087d7524cae::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit382780e3525e50bc2a5e7087d7524cae::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit382780e3525e50bc2a5e7087d7524cae::$classMap;

        }, null, ClassLoader::class);
    }
}
